version: '3'
services:
  GolangApiServer:
    image: ahmedkhalaf666/go-app-api
    container_name: GolangApiServer 
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongodb
  GolangChatService:
    image: ahmedkhalaf666/go-app-chat
    container_name: GolangChatService 
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - app-network
    depends_on:
      - mongodb
      - GolangApiServer

  GolangNotifyService:
    image: ahmedkhalaf666/go-app-notify
    container_name: GolangNotifyService 
    restart: unless-stopped
    ports:
      - "8088:8088"
      - "8090:8090"
    networks:
      - app-network
    depends_on:
      - mongodb
      - GolangApiServer
  VueServer:
    image: ahmedkhalaf666/vue-app-fe
    container_name: VueServer
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network    
    volumes:
      - dist:/dist 
    depends_on:
      - GolangApiServer
      - GolangChatService
      - GolangNotifyService

  mongodb:
    container_name: mongodb
    image: mongo:7.0 
    ports:
      - 27017:27017 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password 
    volumes:
     - mongo-data:/usr/data/db 
    networks:
      - app-network


volumes:
  dist:
    driver: local 
  mongo-data:
    driver:  local

networks:
  app-network:
    driver: bridge


