version: '3'
services:
  GolangApiServer:
    image: ahmedkhalaf666/go-app-api
    container_name: GolangApiServer 
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongodb
      - redis
    environment:
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - JWT_SECRET=o2gfVvPiOyg2YXGQtecK3MdMI6UZkWQ70XSDBQGFOAk=

  VueServer:
    image: ahmedkhalaf666/vue-app-fe
    container_name: VueServer
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network    
    volumes:
      - dist:/dist 
    depends_on:
      - GolangApiServer

  mongodb:
    container_name: mongodb
    image: mongo:7.0 
    ports:
      - 27017:27017 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password 
    volumes:
     - mongo-data:/usr/data/db 
    networks:
      - app-network


  redis:
    container_name: redis
    image: redis:7.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

volumes:
  dist:
    driver: local
  mongo-data:
    driver: local
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge


